In [ ]:
##1

In [1]:
import math
import numpy as np
from decimal import Decimal
import pandas as pd
import random

def euclidean_distance(a, b):
  return math.sqrt(sum([(val1 - val2) ** 2 for val1, val2 in zip(a, b)]))



In [2]:
def manhattan_distance(a, b):
  return sum(abs(val1-val2) for val1, val2 in zip(a,b))

In [3]:
def root(value, root):
  root_value = 1 / float(root)
  return round (Decimal(value) ** Decimal(root_value), 3)

def minkowski_distance(a, b, p_value):
  return (root(sum(pow(abs(x-y), p_value) for x, y in zip(a, b)), p_value))

In [4]:
def cosine_similarity(a, b):
  sumxx, sumxy, sumyy = 0, 0, 0
  for i in range(len(a)):
    x = a[i]; y = b[i]
    sumxx += x*x
    sumyy += y*y
    sumxy += x*y
  return sumxy/math.sqrt(sumxx*sumyy)


In [5]:
def jaccard_similarity(a, b):
    intersection = np.logical_and(a, b)
    union = np.logical_or(a, b)
    similarity = intersection.sum() / float(union.sum())
    return similarity

In [6]:
df = pd.read_csv('/content/C-Lab.csv')
energy = df['energy'].values

In [7]:
A = int(random.choice(energy))
B = int(random.choice(energy))
A = [int(x) for x in str(A)]
B = [int(y) for y in str(B)]

if len(A)<len(B): 
  A.insert(0, 0) 
if len(A)>len(B): 
  B.insert(0, 0) 
A, B

([0, 9, 4], [1, 2, 9])

In [8]:
print( "Euclidean Distance:", euclidean_distance(A, B))
print( "Manhattan Distance:", manhattan_distance(A, B))
print("Minkowski Distance:", minkowski_distance(A, B, 2))
print("Cosine Similarity:", cosine_similarity(A, B))
print("Jaccard Similarity:", jaccard_similarity(A, B))

Euclidean Distance: 8.660254037844387
Manhattan Distance: 13
Minkowski Distance: 8.660
Cosine Similarity: 0.5912330008383061
Jaccard Similarity: 0.6666666666666666


In [ ]:
##2
a11=0*-1 + 1*0 + 1=1
a12=0*0+1*1 +1 =2

a21=1*1 + 2*-1 +1 =0
a22= 1*-1 + 2*1 +1 =2
=> sai số

Ouput:
	denta K = [1-0,0-2] = [1,-2]

Hidden:
	sigma K = [1*-1 + -2*0 , 1*0 + -2 * 1] = [-1,-2]

In [ ]:
##3

In [10]:
from tensorflow.keras import layers
from tensorflow.keras import models
import numpy as np 

In [11]:
import pandas as pd
dataframe = pd.read_csv("iris.csv", encoding='ISO-8859-1')
data = np.array(dataframe.values)
print(data.shape)
print(data[:2])

(149, 5)
[[4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']]


In [ ]:
# i=0
# for i in range(len(data)):
#   for y in range(len(data[i])):
#     # print(data[i][y])
#     b = np.array(data[i][y])
#     data[i][y]=np.setdiff1d(data[i][y],b)
#     break
#   # print(i)
# print(data[:2])
# # data[1][0]

[[array([], dtype=float64) 3.0 1.4 0.2 'Iris-setosa']
 [array([], dtype=float64) 3.2 1.3 0.2 'Iris-setosa']]


In [12]:
X = data[:,:-1]
X = np.asarray(X.astype(np.float))
y = data[:,-1]
print(X.shape)
print(y.shape)

(149, 4)
(149,)


In [13]:
from collections import Counter
counter = Counter()
counter.update(y)
print(counter)

Counter({'Iris-versicolor': 50, 'Iris-virginica': 50, 'Iris-setosa': 49})


In [14]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]


In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)

print('Train:')
print(X_train.shape)
print(y_train.shape)
print('Test:')
print(X_test.shape)
print(y_test.shape)

Train:
(119, 4)
(119,)
Test:
(30, 4)
(30,)


In [16]:
print(X_train[:2])
print(X_train.shape[0])
print(X_train.shape[1])

[[5.7 2.5 5.  2. ]
 [6.1 2.8 4.7 1.2]]
119
4


In [17]:
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train)
print(y_train[:2])

[[0. 0. 1.]
 [0. 1. 0.]]


In [18]:
model = models.Sequential()
model.add(layers.Dense(20, activation='relu'))
model.add(layers.Dense(10, activation='relu'))
model.add(layers.Dense(8, activation='relu'))
model.add(layers.Dense(3, activation='sigmoid'))
model.compile(loss='categorical_crossentropy', optimizer='adam', 
              metrics=['accuracy'])

In [19]:
model.fit(X_train,y_train,epochs=150, batch_size=10, verbose=2)

Epoch 1/150
12/12 - 1s - loss: 1.0138 - accuracy: 0.3277 - 691ms/epoch - 58ms/step
Epoch 2/150
12/12 - 0s - loss: 0.9578 - accuracy: 0.4118 - 19ms/epoch - 2ms/step
Epoch 3/150
12/12 - 0s - loss: 0.9141 - accuracy: 0.6723 - 17ms/epoch - 1ms/step
Epoch 4/150
12/12 - 0s - loss: 0.8660 - accuracy: 0.6891 - 15ms/epoch - 1ms/step
Epoch 5/150
12/12 - 0s - loss: 0.8188 - accuracy: 0.6891 - 15ms/epoch - 1ms/step
Epoch 6/150
12/12 - 0s - loss: 0.7737 - accuracy: 0.6891 - 17ms/epoch - 1ms/step
Epoch 7/150
12/12 - 0s - loss: 0.7287 - accuracy: 0.6891 - 22ms/epoch - 2ms/step
Epoch 8/150
12/12 - 0s - loss: 0.6892 - accuracy: 0.6891 - 16ms/epoch - 1ms/step
Epoch 9/150
12/12 - 0s - loss: 0.6521 - accuracy: 0.6891 - 15ms/epoch - 1ms/step
Epoch 10/150
12/12 - 0s - loss: 0.6204 - accuracy: 0.6891 - 16ms/epoch - 1ms/step
Epoch 11/150
12/12 - 0s - loss: 0.5902 - accuracy: 0.6891 - 16ms/epoch - 1ms/step
Epoch 12/150
12/12 - 0s - loss: 0.5626 - accuracy: 0.6891 - 19ms/epoch - 2ms/step
Epoch 13/150
12/12 - 0s

In [20]:
y_pred = model.predict(X_test)
print(y_pred[:2])

[[0.74681246 0.99913883 0.15195379]
 [0.00836658 0.98021156 0.4117432 ]]


In [21]:
y_pred = y_pred.argmax(axis=1)
print(y_pred)
print(y_test)

[1 1 1 0 2 0 2 0 2 0 2 1 1 2 0 2 2 1 1 2 2 0 1 1 1 1 2 1 2 1]
[1 1 1 0 2 0 2 0 2 0 2 1 1 2 0 2 2 1 1 2 2 0 1 1 1 1 2 1 2 1]


In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

