In [ ]:
##1 Vào 1 đường dẫn đến tập các file text (chỉ vào thư mục, tên file và số lượng file không biết), in ra các từ và số lượng 
##các từ trong tất cả các file đó, giả sử các từ cách nhau bởi khoảng trắng.
import os
from collections import Counter

# Folder Path in Colab
path = "/content/exercise1"
# Change the directory
os.chdir(path)
# Read text File
def read_text_file(file_path):
  with open(file_path, 'r') as f:
    data = f.read()
  return data.split()

words = []
for file in os.listdir():
  if file.endswith(".txt"):
    file_path = f"{path}/{file}"
    read_text_file(file_path)
    global words
    #Merge words of all file:
    if words is None:
      words = read_text_file(file_path)
    else:
      words.extend(read_text_file(file_path))
#Count numbers of specific words
result = Counter(words)
for r in result:
        print (r, ':', result[r])

World : 3
I : 1
am : 1
Hello : 4


In [ ]:
##2
x = {'key1' : 1, 'key2' : '3', 'key3' : '2'}
y={'key1' : 1, 'key2' : '2'}

for key, val in x.items():
  for key2, val2 in y.items():
    if(key==key2 and val==val2):
      print(key + ":" + str(val))

key1:1


In [ ]:
##3
import json 
      
dictionary ={
  'students': [
               {'firstName': 'Nikki', 'lastName': 'Roysden'}, 
               {'firstName': 'Mervin', 'lastName':'Friedland'}, 
               {'firstName': 'Aron ', 'lastName': 'Wilkins'}
  ], 
  'teachers': [
               {'firstName': 'Amberly','lastName': 'Calico'}, 
               {'firstName': 'Regine', 'lastName': 'Agtarap'}
  ]
}
      
json_object = json.dumps(dictionary, indent = 4) 
print(json_object)

with open("cau3.json", "w") as outfile:
    json.dump(dictionary, outfile)

{
    "students": [
        {
            "firstName": "Nikki",
            "lastName": "Roysden"
        },
        {
            "firstName": "Mervin",
            "lastName": "Friedland"
        },
        {
            "firstName": "Aron ",
            "lastName": "Wilkins"
        }
    ],
    "teachers": [
        {
            "firstName": "Amberly",
            "lastName": "Calico"
        },
        {
            "firstName": "Regine",
            "lastName": "Agtarap"
        }
    ]
}


In [1]:
##4
import numpy as np


In [ ]:
#the multiplication of two given matrixes.
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[1,3],[2,4],[7,8]])
m3 = np.dot(m1,m2) 
print(m3) 

[[26 35]
 [56 80]]


In [ ]:
#the outer product of two given vectors
m1 = np.array([[1, 5], [7, 9]])
m2 = np.array([[5, 3], [6, 8]])
result = np.outer(m1, m2)
print(result)

[[ 5  3  6  8]
 [25 15 30 40]
 [35 21 42 56]
 [45 27 54 72]]


In [ ]:
#the cross product of two given vectors
m1 = np.array([[1, 5], [7, 9]])
m2 = np.array([[5, 3], [6, 8]])
result = np.cross(m1, m2)
print(result)

[-22   2]


In [ ]:
#the determinant of a given square array
from numpy import linalg

matrix = np.array([[1, 2, 5], [15, 3, 9], [8, 7, 3]])
print(np.linalg.det(matrix))

405.0000000000002


In [4]:
#the determinant of an array
matrix = np.array([[3,5],[15,6]])
result =  np.linalg.det(matrix)
print(result)

-57.00000000000001


In [ ]:
#the inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension

a1 = np.array([1,5,6,3])
a2 = np.array([3,5,7,9])

result = np.inner(a1, a2)
print(result)

97


In [ ]:
##5) Xây dựng cấu trúc Stack theo cú pháp sau:
class Stack:
  def __init__(self):
    self.st=[]
  def push(self, el):
    self.st.append(el)
  def pop(self):
    return self.st.pop()
  def isEmpty(self):
    return self.st == []
  def size(self):
    return len(self.st)
  def top(self):
    return self.st[-1]

if __name__ == '__main__':
  st = Stack()
  st.push(5)
  st.push(7)
  st.push(9)
  print(st.pop())
  print(st.top())

9
7


In [ ]:
##sử dụng Stack để nhập vào 1 số ở dạng thập phân, in ra số đó ở hệ nhị phân tương ứng.
dec=int(input('Nhap so can chuyen doi: '))
print('Decimal num: ', dec)
result=''

st1= Stack()
while dec>0:
  flag=dec%2
  st1.push(flag)
  dec=dec//2
while st1.isEmpty() == False:
  result = result + str(st1.top())
  st1.pop()

print('Binary num: ', result)

Nhap so can chuyen doi: 10
Decimal num:  10
Binary num:  1010


In [ ]:
##6: Viết các hàm để tính các số phép toán + - * / với các số nguyên lớn
def Add(bigIntA,bigIntB):
  return bigIntA + bigIntB
def Sub(bigIntA, bigIntB):
  return bigIntA - bigIntB
def Mul(bigIntA, bigIntB):
  return bigIntA * bigIntB
def Div(bigIntA, bigIntB):
  return bigIntA // bigIntB
if __name__ == '__main__':
  a= int(1000**100)
  b= int(2**100)
  print('Add: ', Add(a,b))
  print('Sub: ', Sub(a,b))
  print('Mul: ', Mul(a,b))
  print('Div: ', Div(a,b))

Add:  1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001267650600228229401496703205376
Sub:  999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999998732349399771770598503296794624
Mul:  1267650600228229401496703205376000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Div:  78886090522101180541172856528278622967320